name: Scheduled Ping Job

on:
  schedule:
    # ┌───────────── minute (0 - 59)
    # │ ┌───────────── hour (0 - 23)
    # │ │ ┌───────────── day of the month (1 - 31)
    # │ │ │ ┌───────────── month (1 - 12)
    # │ │ │ │ ┌───────────── day of the week (0 - 6)
    # │ │ │ │ │
    # │ │ │ │ │
    - cron: "*/15 * * * *"  # every hour
  workflow_dispatch:      # allows manual runs from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping FastAPI Endpoint
        run: |
          echo "Pinging API endpoint..."
          curl -X GET https://delightful-cliff-0aa2bd010.3.azurestaticapps.net/songs/worship
